version: '2'
services:
  jekyll:
    build:
      context: .
      dockerfile: ./build-environment/Dockerfile
    image: lil-website:0.4
    command: bash
    tty: true
    volumes:
        - ./app:/usr/src/lil-website/app
        - ./assets:/usr/src/lil-website/assets
        - ./builds:/usr/src/lil-website/builds
  server:
    image: httpd
    ports:
        - "8080:8080"
        - "8081:8081"
    volumes:
        - ./builds/dev:/usr/local/apache2/htdocs/dev
        - ./builds/prod:/usr/local/apache2/htdocs/prod
        - ./build-environment/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./build-environment/apache/logs:/usr/local/apache2/logs

